# Този файл е входната точка за конфигуриране на вашите услуги.
# Файловете в поддиректорията packages/ конфигурират вашите зависимости.

# Поставете параметри тук, които не се нуждаят от промяна на всяка машина, където приложението се развива
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    weather.config:
        url:
            current: 'http://api.openweathermap.org/data/2.5/weather'
            forecast: 'http://api.openweathermap.org/data/2.5/forecast'
        apiKey: '%env(WEATHER_API_KEY)%'
        cacheTtl: 3600 # 1 hour

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            array $weatherConfig: '%weather.config%'

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Add more service definitions when explicit configuration is needed
    # Please note that last definitions always *replace* previous ones
